<?php

// use \OopToolkitModule as OopToolkitModule;

/**
 * @file oop_toolkit.module
 * Initial module file for OOP Toolkit module.
 * TODO: Add actual content of the module file.
 */

/**
 * Form builder.
 *
 * @param $form
 * @param $form_state
 * @param bool $getName
 * @return string
 */
function oop_toolkit_settings_form($form, &$form_state, $getName = FALSE) {
  if ($getName) {
    return __FUNCTION__;
  }

  $form['oop_toolkit_variable_foo'] = array(
    '#type' => 'textfield',
    '#title' => t('Foo'),
    '#default_value' => variable_get('oop_toolkit_variable_foo', 42),
    '#required' => TRUE,
  );

  // TODO! You probably don't need validation or submit handlers if using system_settings_form().
  return system_settings_form($form);
}

/**
 * Form validate handler.
 */
function my_module_settings_form_validate($form, &$form_state) {
  if ($form_state['values']['element'] != 'hello') {
    form_set_error('element', t('Please say hello?'));
  }
}

/**
 * Form submit handler.
 */
function my_module_settings_form_submit($form, &$form_state) {

}

/**
 * Implements hook_menu().
 */
function oop_toolkit_menu() {
  $module = OopToolkitModule::getInstance();
  $callbackName = oop_toolkit_settings_form(null, new stdClass(), TRUE);
  print_r($callbackName);

  $items = array();

  $items[$module->getAdminPath()] = array(
    'title' => 'OPP Toolkit Administration',
    'description' => 'Configuration and adminstration pages for OOP Toolkit module.',
    'page callback' => 'drupal_get_form',
    // 'page arguments' => array('oop_toolkit_settings_form'),
    'page arguments' => array($callbackName),
    'access arguments' => array('administer OOP toolkit'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 * @return string Help text wrapped in t() and paragraph.
 */
function oop_toolkit_help($path, $arg) {
  $module = OopToolkitModule::getInstance();
  switch ($path) {
    case $module->getHelpPath():
      return $module->getFormattedHelpText();
      break;
  }
}
