<?php

use \ExampleVariable as ExampleVariable;

/*
 * @file
 * Example module file creating administration page with usage of Variable class.
 */

/**
 * Implements hook_menu().
 * Example administration page using Variable class.
 * @return array System settings form structure.
 */
function oop_toolkit_example_admin() {
  $form = array();

  $exampleVar = new ExampleVariable();

  $form['oop-toolkit-example_admin'] = array(
    '#type' => 'textfield',
    '#title' => t('Example variable value'),
    '#default_value' => $exampleVar->getDefault(),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
