<?php

/**
 * @file
 * File oop_toolkit_example.module.
 *
 * Example module file creating administration page,
 * with usage of Variable class.
 */

module_load_include('inc', 'oop_toolkit_example', 'includes/callbacks');

/**
 * Implements hook_menu().
 */
function oop_toolkit_example_menu() {

  /* @var $module \OopToolkitExampleModule */
  $module = OopToolkitExampleModule::getInstance();

  $form = new Form($module->getAdminPath(), 'Example administration for OPP Toolkit module');
  $form->setDescription('Example administration pages for OOP Toolkit module.');
  $form->setPageCallback('drupal_get_form');
  $form->setPageArguments(array('oop_toolkit_example_settings_form'));
  $form->setAccessArguments(array('administer OOP toolkit'));
  $form->setType(MenuItem::MENU_NORMAL_ITEM);

  return $form->getForm();
}

/**
 * Implements hook_help().
 */
function oop_toolkit_example_help($path, $arg) {
  /* @var $module OopToolkitExampleModule */
  $module = OopToolkitExampleModule::getInstance();

  switch ($path) {
    case ($module->getHelpPath()):
      return $module->getFormattedHelpText();
  }
}
